### ISSUE TITLE
Namespace Meta-Issue

### ISSUE THREAD

**Issue by ddiakopoulos** [ddiakopoulos/LabSound#36]
Both WebCore and LabSound namespaces are intermingled, and "using" declarations are used in headers, which could be considered a best-practices no-no.

Plan of attack: re-tool project under a single namespace, "lab" and ensure no using declarations are present in .h files.

**Comment by meshula** [comment]
It's becoming it's own thing little by little...

**Comment by meshula** [comment]
I suggest pushing a 0.9.0 tag before starting the namespace renaming. I've been thinking about tagging a 1.0.0, and I think that right after a namespace transmogrification would be quite suitable.

**Comment by meshula** [comment]
a convention like LabSound-x.y.z would probably be nice, where y indicates possibly breaking API changes, and x is definitely breaking changes.

**Comment by ddiakopoulos** [comment]
Yeah, an approximation of semver as we approach a 1.0.0 is nice. Are you ok with the lab:: namespace? "Lowercase 3 characters" seems in line with many little C++ libraries. Speaking of a 1.0, I'll file an issue on that because I had a couple low-priority issues to file before that milestone.

**Comment by meshula** [comment]
lab:: is cool.

**Comment by ddiakopoulos** [comment]
Fixed primarily in 4d999033370780679bc2d27b52972db351841752 and several minor followup commits
