### ISSUE TITLE
Coding Style Meta-Issue

### ISSUE THREAD

**Issue by ddiakopoulos** [ddiakopoulos/LabSound#37]
Google/Chromium/Webkit authors have one style, and I've been adopting Allman/BSD style brackets with the usual exception for single-line statements, etc. Preferred indent is 2 tabs of 4 spaces each. 

With C++11, constructor initialization of member variables isn't strictly needed in most cases, and can be done in the header instead. 

Plan of attack: renormalize codebase to single coding convention.

**Comment by meshula** [comment]
What do you mean by preferred indent is 2 tabs of 4 spaces? Indent of what vs. what?

**Comment by ddiakopoulos** [comment]
I think I just mean 2 tabs, where the length of each tab is equivalent to 4 spaces?

**Comment by meshula** [comment]
Right now we have

void func()
{
....if (whatever)
....{
........yupUhHuh();
....}
}
where each indent level increases by one tab equal to four spaces, or alternately
void func()
{
Tif (whatever)
T{
TTyupUhHuh();
T}
}

Where T is a tab. I'm not mentally mapping the two tabs 4 spaces verbiage to that, but if that's how it shakes out, cool :)

**Comment by ddiakopoulos** [comment]
Haha, yeah, option B I think. Tabs! Tabs in all the places.

**Comment by meshula** [comment]
LOL, dangerously close to a vi vs emacs debate ;) ((( my answer - Sublime, with an occasional dabble in Atom to see if it's cooked yet ;)))

**Comment by ddiakopoulos** [comment]
Normalized spaces in 7c37ef1a2de1a9fbdaab94e3684d7983cb318ae5.
